Разметка HTML главной страницы
htmlacademy-adaptive/1355873-mishka-22 pull request #2
Opened 2021-03-29 20:21 UTC by stanislauhvozdz

2021-03-30 08:07 UTC, mikhin requested changes

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +          <a href="catalog.html">Каталог товаров</a>
давай добавим ссылкам классы

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +      <h2 class="hero__title">Милые штуки ручной работы для дома</h2>
Может это и сделать h1, а тот скрытый убрать? Они как будто повторяют друг друга и пользы в этом мало

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +    <section class="hero">
Однословные имена классов — почти всегда неполезно, т.к. ничего не говорит о том, что это за элемент. Вот мы открываем список БЭМ-блоков, видим `hero`, и не понимаем что это компонент в интерфейсе? Для чего он нужен и как используется? Непонятно, потому что не хватает термина из нашей с тобой профессиональной области — разработка интерфейсов. Если в именованиях использовать термины из разработки интерфейсов + термины из бизнес-области проекта, то почти всегда именования будут понятны сразу после прочтения, без необходимости глубже погружаться в код)

Вот тут еще глянуть можно — https://github.com/yoksel/common-words

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +          <a href="#">Предметы <br> интерьера</a>
Не должны хотеть пока вот так специально разрывать строки)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +    <section class="product-discount">
Не совсем понятно почему `product-discount` если это товар недели)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +      <h2 class="product-discount__title">ТОВАР НЕДЕЛИ</h2>
по-моему сейчас перепутаны настоящий заголовок и пояснение)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +          <dt class="product-discount__characteristic">Цвет:</dt>
Лайк за семантику)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +      <button class="product-discount__button">ЗАКАЗАТЬ</button>
если изменится на ссылку, то тогда бэм-именование будет противоречивым) давай назовем __action

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +      <div class="about-feedback">
`about-feedback` непонятно что значит

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +        <ul class="about-slider__list">
не хватает родительского блока у этого элемента

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +          <li class="about-slider__item">Я молодая мама, но всё равно фотографии не набирали и близко такого количества лайков, как
А в макете есть другие слайды? Давай их сразу разметим?

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +          <button type="button" aria-label="Посмотреть предидущий отзыв">
нужен класс)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +            <img src="img/icon-huge-arrow-left.svg" aria-hidden="true">
нужен класс)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +          <dd class="contacts__value">info@mimimishkashop.ru</dd>
давай сразу ссылку сделаем)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +      <button class="contacts__button" type="button">НАпишите нам</button>
опечатка в заглавных буквах

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +        <a href="#">
нужен класс)

2021-03-30 08:07 UTC, mikhin commented on source/index.html
> +    <a href="#">
нужен класс)

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +      <h2 class="product-discount__title">ТОВАР НЕДЕЛИ</h2>
я шел с такой логики что, это секция - распродажа \ акция \ хит продаж , поэтому написал H2 товар недели, т.к на следующей неделе туда можно будет подставить "вязаные шапки". 
Название секции мне кажется тут важнее чем шапки или корзинки))

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +      <ul class="main-nav__list site-list">
Украл из лекции ))

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +          <a href="catalog.html">Каталог товаров</a>
ок

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +          <a href="#">Предметы <br> интерьера</a>
понял)

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +      <button class="product-discount__button">ЗАКАЗАТЬ</button>
ты намекаешь на кнопку ?)

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +          <li class="about-slider__item">Я молодая мама, но всё равно фотографии не набирали и близко такого количества лайков, как
Есть, нашел) добавлю без вопросов

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +          <button type="button" aria-label="Посмотреть предидущий отзыв">
согласен

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +          <dd class="contacts__value">info@mimimishkashop.ru</dd>
верно подмечено )

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +        <a href="#">
понял)

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +    <a href="#">
понял)

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +      <button class="contacts__button" type="button">НАпишите нам</button>
понял

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +    <section class="hero">
как примерно его назвать можно адекватно? ) promo-block?

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +      <h2 class="hero__title">Милые штуки ручной работы для дома</h2>
я подправлю H1, 

H1 - Магазин Мишка - магазин изделий ручной работы

2021-03-30 16:33 UTC, stanislauhvozdz commented on source/index.html
> +            <img src="img/icon-huge-arrow-left.svg" aria-hidden="true">
сделаю

2021-03-31 07:42 UTC, mikhin commented on source/img/icon-fb.svg
> +<svg width="15" height="28" viewBox="0 0 15 28" fill="none" xmlns="http://www.w3.org/2000/svg">
Вроде картинки еще рано готовить?)

2021-03-31 07:44 UTC, mikhin commented on source/index.html
> +      <ul class="main-nav__list site-list">
не, ну я имею ввиду, что непонятно что это значит) давай сделаем понятно?)

2021-03-31 07:44 UTC, mikhin commented on source/index.html
> +    <section class="hero">
да, типа того)

2021-03-31 07:44 UTC, mikhin commented
@stanislauhvozdz , проверки в пулл реквесте упали

2021-03-31 07:45 UTC, mikhin commented on source/index.html
> +      <h2 class="product-discount__title">ТОВАР НЕДЕЛИ</h2>
хм, интересная мысль) давай тогда оставим, да)

2021-03-31 07:45 UTC, mikhin commented on source/index.html
> +      <button class="product-discount__button">ЗАКАЗАТЬ</button>
не понял вопрос?)

2021-03-31 07:46 UTC, mikhin commented on source/index.html
> +    <section class="main-billboard">
`main-billboard` чутка косноязычно звучит) давай поправим на `promo-block`

2021-03-31 07:46 UTC, mikhin commented on source/index.html
> +    <h1 class="visually-hidden">Магазин Мишка - интернет-магазин по реализации элементов декора от кутюр</h1>
По прежнему пока непонятно зачем тут нужен скрытый заголовок и почему нельзя сделать h1 следующий заголовок, который явно видно в дизайне) Расскажешь?)

2021-03-31 07:51 UTC, mikhin requested changes

2021-03-31 07:51 UTC, mikhin commented on source/index.html
> +      <div class="about-us__customer-feedback customer-feedback slider">
Давай вынесем отзывы из секции "О нас"? Иначе "О нас" получается уж очень жирный БЭМ-блок

2021-03-31 07:51 UTC, mikhin commented on source/index.html
> +      <div class="about-us__customer-feedback customer-feedback slider">
Без учета `about-us__customer-feedback` непонятно зачем сразу нужный два БЭМ-блока на одной HTML-ноде `customer-feedback slider` и как эти БЭМ-блоки использовать по отдельности, если захочется.

2021-03-31 07:51 UTC, mikhin commented on source/index.html
> +        <ul class="customer-feedback__list slider__list">
непонятно зачем сразу нужны два БЭМ-элемента на одной HTML-ноде и как эти БЭМ-блоки использовать по отдельности, если захочется.

2021-03-31 07:51 UTC, mikhin commented on source/index.html
> +            <blockquote class="customer-feedback__blockquote blockquote">Я двоюродная сестра молодой мамы, но всё равно фотографии не набирали и близко такого количества лайков, как у популярных инст
Лайк за семантику)

2021-03-31 15:07 UTC, stanislauhvozdz commented on package.json
> -{
Этот файл я сделал сам, своя сборка) но я понял что нам дадут от HTML, я свои удалил

2021-03-31 15:21 UTC, stanislauhvozdz commented on source/index.html
> +    <h1 class="visually-hidden">Магазин Мишка - интернет-магазин по реализации элементов декора от кутюр</h1>
секундочку)) 
если не ошибаюсь , Х1 помогает при поиске (сео),  с больше вероятностью буду искать "интернет магазин" чем "Милые штуки ручной работы для дома"
+ я прочел что <title> должен быть похож на Н1, с текущим "Магазин Мишка - интернет-магазин" он совпадает)) хоть и одним словом.
Если мы поставим "Милые штуки ручной работы для дома" то не добьемся и этого)) 
Вот с такими мыслями я и защищаю данный Н1 )))

2021-03-31 15:38 UTC, stanislauhvozdz commented on source/index.html
> +      <div class="about-us__customer-feedback customer-feedback slider">
customer-feedback - тут сделать все стили для списка, а тут slider настроить только slider
Но из макета можно сделать вывод что слайдера больше не будет , можно все повесть на  customer-feedback как вариант

2021-03-31 15:55 UTC, stanislauhvozdz commented on source/index.html
> +      <div class="about-us__customer-feedback customer-feedback slider">
разбил на 2

2021-03-31 15:58 UTC, stanislauhvozdz commented on package.json
> -{
С академии еще не загружал

2021-04-02 08:15 UTC, merged