Module2-task3
htmlacademy-adaptive/1355873-mishka-22 pull request #4
Opened 2021-04-06 16:34 UTC by stanislauhvozdz

Разметка catalog

Исправлен order-form, добавлено модальное окно в index

2021-04-06 19:50 UTC, mikhin requested changes

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +      <h1 class="catalog__title">Каталог товаров</h1>
Давай сделаем так, чтобы на страницах формы и каталога этот заголовок страницы был бы одинаковым БЭМ-блоком?)

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +          <article class="cart">
cart, это «корзина», непонятно причем она здесь)

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +              <div class="cart__descr">
descr > description

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +              <div class="cart__cost-block">
слово block можно никогда не использовать, т.к. оно не добавляет пользы и смысла)

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +                <h2 class="cart__product-name">Зайчик-попрыгайчик</h2>
лучше вынести заголовок из контейнера description

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +                <p class="cart__characteristic">Рост 30 см, вес 200 г</p>
characteristic непонятно что за характеристика, как раз это мог бы быть description

2021-04-06 19:50 UTC, mikhin commented on source/catalog.html
> +    <section class="production-process">
production-process-section

в именах БЭМ-блоков, помимо бизнес-терминов, еще важно указывать термины из области разработки интерфейсов)

2021-04-06 19:50 UTC, mikhin commented on source/index.html
> +    <form class="modal__form-size" action="https://echo.htmlacademy.ru" method="POST">
__form-size непонятно что означает)

2021-04-06 19:50 UTC, mikhin commented on source/index.html
> +    <form class="modal__form-size" action="https://echo.htmlacademy.ru" method="POST">
А тут форма по дизайну похожа на форму со страницы формы? Мы могли бы использовать те же самые БЭМ-блоки?

2021-04-06 19:50 UTC, mikhin commented on source/order-form.html
> +      <label class="text-field">
Лейбл не должен относиться к блоку инпута, он должен относиться к блоку поля, чтобы в него можно было вложить какой-угодно инпут)

2021-04-08 09:38 UTC, mikhin approved these changes

2021-04-08 09:38 UTC, mikhin commented on source/index.html
> +        <label class="radio" aria-label="Размер S">
Однословные имена классов это почти всегда плохо, т.к. непонятно что это за компонент, что он делает и для чего используется

2021-04-08 09:38 UTC, mikhin commented on source/index.html
> +        <label class="radio" aria-label="Размер S">
Надо бы разделить поле и инпут поля в каждом случае на отдельные БЭМ-блоки — чтобы блока поля отвечал за лейбл и в него можно было бы вложить любой блок инпута

2021-04-08 09:38 UTC, merged

2021-04-08 16:00 UTC, stanislauhvozdz commented on source/index.html
> +        <label class="radio" aria-label="Размер S">
как примерно это сделать, что-то я в толк не возьму