module3-task1
htmlacademy-adaptive/1355873-mishka-22 pull request #5
Opened 2021-04-13 20:05 UTC by stanislauhvozdz

2021-04-15 09:58 UTC, mikhin requested changes

2021-04-15 09:58 UTC, mikhin commented on source/sass/common.scss
> +.unselectable {
Хм, а расскажи, плиз, для чего такое нужно?)

2021-04-15 09:58 UTC, mikhin commented on source/sass/common.scss
> +  margin: 0 auto;
На БЭМ-блоке не должно висеть правил «внешней геометрии» — тех правил, которые выравнивают блок в его окружении. Например, margin, position: absolute, flex-grow и т.д. Мы должны хотеть проектировать абсолютно-независимые блоки, которые ничего не знают о тех местах употребления, где они применяются.

2021-04-15 09:58 UTC, mikhin commented on source/sass/common.scss
> +  &--no-padding {
Странно, а зачем контейнеру нужен такой модификатор?

2021-04-15 09:58 UTC, mikhin commented on source/sass/common.scss
> +    max-width: $desktop;
Зачем нужна такая максимальная ширина?)

2021-04-15 09:58 UTC, mikhin commented on source/sass/common.scss
> +    padding: 0 50px;
Дублируется значение из предыдущего медиа-выражения)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/promo-block.scss
> +  &:nth-child(odd) {
лайк)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/promo-block.scss
> +.promo-block-list {
Если это отдельный БЭМ-блок, он должен быть в отдельном файле)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/promo-block.scss
> +  margin-top: -35px;
На БЭМ-блоке не должно висеть правил «внешней геометрии» — тех правил, которые выравнивают блок в его окружении. Например, margin, position: absolute, flex-grow и т.д. Мы должны хотеть проектировать абсолютно-независимые блоки, которые ничего не знают о тех местах употребления, где они применяются.

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/promo-block.scss
> +    .br {
Стили одного БЭМ-блока не должны влиять на стили другого БЭМ-блока)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/promo-block.scss
> +  position: absolute;
А точно тут нужно абсолютное позиционирование?

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/promo-block.scss
> +.promo-block-container {
Если это отдельный БЭМ-блок, он должен быть в отдельном файле)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/product-week.scss
> +.product-week-container {
Если это отдельный БЭМ-блок, он должен быть в отдельном файле)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/page-footer.scss
> +.social-list {
Если это отдельный БЭМ-блок, он должен быть в отдельном файле)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +.delivery-slogan {
Если это отдельный БЭМ-блок, он должен быть в отдельном файле)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +  display: none;
Блок не должен хотеть скрывать сам себя)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +.sale-nav {
Если это отдельный БЭМ-блок, он должен быть в отдельном файле)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +  display: none;
Блок не должен хотеть скрывать сам себя) проверь плиз во всех местах)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +  margin-left: 76px;
А почему именно так?

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +    display: inline-block;
А зачем менять display?

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +  &--active {
Непонятный модификатор для user-nav

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +  box-shadow: 0 1px 0 #ececec, inset 0 1px 0 #ececec;
Давай использовать для цветовых значений переменные)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +  &--active {
Странный модификатор для main-nav

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +    display: inline-block;
Для чего нужно?)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/header.scss
> +    position: absolute;
Точно нужно абсолютное позиционирование?

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/customer-feedback.scss
> +.customer-feedback__button {
В общем, каждый отдельный БЭМ-блок нужно вынести в свой отдельный файл)

2021-04-15 09:58 UTC, mikhin commented on source/sass/blocks/contacts.scss
> +    right: calc(100% / 2 - 525px);
Непонятно что значит 525, это «магическое число»:

https://ru.hexlet.io/blog/posts/magic-numbers

Давай завернем в переменную?

2021-04-15 09:58 UTC, mikhin commented on source/js/navigation-toggle.js
> +const mainNavigation = document.querySelector('.main-nav');
Давай разделим скрипт также на несколько модулей (файлов), где каждый модуль будет представлять свой отдельный БЭМ-блок? Правило такое — внутри JS, также как и внутри SASS нельзя смешивать классы из разных БЭМ-блоков, потому что это хрупкая и связанная конструкция. Блоки должны быть разделены и должны представлять друг другу функции для управления собой.

2021-04-15 09:58 UTC, mikhin commented on source/index.html
>      <form class="modal__form-choice-size" action="https://echo.htmlacademy.ru" method="POST">
Давай форму вынесем в отдельный БЭМ-блок? Непонятно почему модалка хочет знать про форму, модалка не должна хотеть знать про свой контент, т.к. в нее можно вложить любой контент)

2021-04-15 09:58 UTC, mikhin commented on source/index.html
> +        svg use html academy
Давай вот эти штуки все уже заменим на настоящие картинки? Или уберем пока вообще?) На первых этапах было более-менее норм, но сейчас уже непонятно что от этого ждать и что это за код вообще)

2021-04-15 09:58 UTC, mikhin commented on source/index.html
> +            <img src="img/icon-huge-arrow-left.svg" aria-hidden="true" alt="Посмотреть предыдущий отзыв">
Лайк за alt, хотя он и не совсем точный – alt должен описывать именно сам изображение. Давай эти картинки вынесем в стили, они ведь декоративные?)

2021-04-15 09:58 UTC, mikhin commented on source/index.html
> +            <div class="blockquote__author">Елена Красильникова
БЭМ-элементы лежат вне своего родительского БЭМ-блока)

2021-04-15 09:58 UTC, mikhin commented on source/index.html
> +          <li class="about-us-list__item">Экологически чистые материалы</li>
Тут кажется опечатка в БЭМ-блоках

2021-04-15 10:00 UTC, mikhin commented
В пулл реквесте не прошла проверка

2021-04-15 10:03 UTC, mikhin commented on source/sass/blocks/contacts.scss
> +    position: absolute;
Кажется здесь можно обойтись без абсолютного позиционирования)

Давай по возможности избавимся от него во всем проекте? Не стоит им злоупотреблять, особенно для контентных блоков — все по возможности должны оставаться в потоке. Position: absolute это нечастый прием, применяемый скорее для позиционирования декора или в таком духе

2021-04-15 10:05 UTC, mikhin commented
По визуальному состоянию проекта непонятно что в итоге должно получится в этом задании? Сейчас смущает, что как будто сделано наполовину (см. скриншот): то ли мы должны были сделать только минимальные стили для текстов, то ли мы уже делаем сетки по полной. Сейчас где-то есть сетки, где-то нет, непонятно.

<img width="1131" alt="Screenshot 2021-04-15 at 13 02 26" src="https://user-images.githubusercontent.com/38258318/114852022-10d1ea80-9deb-11eb-8ffb-d9164c7393e4.png">

2021-04-18 14:23 UTC, stanislauhvozdz commented on source/sass/style.scss
> +@import "../../node_modules/normalize-scss/sass/normalize/import-now";
пробовал как ты написал, выдает ошибку (( 
оставил так же как и есть

2021-04-18 14:23 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +$wite-hover: rgba($white, 0.6);
исправил

2021-04-18 14:23 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +$wite-down: rgba($white, 0.3);
исправил

2021-04-18 14:24 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +$color-secondary-50: #63d1bb;
https://ux.pub/novyy-podhod-k-podboru-tsveta-v-interfeyse/

я придерживался этой концепции, но если что, я могу переделать ))

2021-04-18 14:24 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +$black-hover: rgba($black, 0.6);
согласен, маханул лишнего))

2021-04-18 14:24 UTC, stanislauhvozdz commented on source/index.html
>      <form class="modal__form-choice-size" action="https://echo.htmlacademy.ru" method="POST">
Слелал, форму отдельны блоком

2021-04-18 14:25 UTC, stanislauhvozdz commented on source/index.html
> +        svg use html academy
заменил, внес в спрайт

2021-04-18 14:25 UTC, stanislauhvozdz commented on source/index.html
> +            <img src="img/icon-huge-arrow-left.svg" aria-hidden="true" alt="Посмотреть предыдущий отзыв">
замнеил на бекграунд

2021-04-18 14:25 UTC, stanislauhvozdz commented on source/index.html
> +            <div class="blockquote__author">Елена Красильникова
испрвил, внес все в бэм блок

2021-04-18 14:25 UTC, stanislauhvozdz commented on source/index.html
> +          <li class="about-us-list__item">Экологически чистые материалы</li>
Зоркий глаз)) я не заметил) исправил

2021-04-18 14:27 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +    position: absolute;
Оставил так все же в абсолюте, ни чего не придумал лучшего, если сможешь толкнут ь в сторону чтобы без абсолюта это сделать)) буду очень благодарен

2021-04-18 17:49 UTC, undgrnd commented
@stanislauhvozdz , проверки в ПР не прошли

2021-04-18 18:11 UTC, undgrnd requested changes
@stanislauhvozdz , сейчас глобально два замечания:

1. Остались неотвеченными мои комменты. Почему? Тяжело понимать в таком большом пулл реквесте что происходит, поэтому нужен диалог и инициатива по объяснению от автора (от тебя)
2. В коммите с правками прилетело очень много нового функционала — проверять и обсуждать становится тяжело, непонятно где правки, а где новые фичи, проверка затягивается, плюс ты получаешь новые правки на свои новые фичи)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/contacts.scss
> +  @media (min-width: $tablet) {
Медиа-выражения селектора должны идти до вложенных селекторов

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/contacts.scss
> +    left: 290px;
По идее не должны хотеть такого — смещать позиционирование. Почему не можем обойтись стандартными методам для создания раскладки?

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
> +    margin-bottom: 115px;
На БЭМ-блоке не должно висеть правил «внешней геометрии» — тех правил, которые выравнивают блок в его окружении. Например, margin, position: absolute, flex-grow и т.д. Мы должны хотеть проектировать абсолютно-независимые блоки, которые ничего не знают о тех местах употребления, где они применяются.

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
> +  @media (min-width: $tablet) {
Медиа-выражения для основного селектора должны идти до вложенных селекторов

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
>  .customer-feedback-container {
Нужно вынести в отдельный файл

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
> +    padding-left: calc(((100% - 768px) / 2.183) + 50px);
Оч сложно читать и понимать) можем упростить?)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
>  .blockquote__author {
Нужно вынести в отдельный файл)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
> +    margin-top: calc((((100% - 768px) * 0.0419) * -1) + 60px);
Очень сложно читать и понимать) можем упростить?)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/customer-feedback.scss
>  .slider-control__prev,
Нужно вынести в отдельный файл

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/header.scss
>  .page-header-container {
Нужно вынести в отдельный файл

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/header.scss
> +.page-header {
Файл должен называться также как и основной класс БЭМ-блока в нем)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/header.scss
> +      span {
По БЭМ-нельзя стилизовать теги, а только классы)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/header.scss
> +  span {
По БЭМ нельзя стилизовать теги, а только классы)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/header.scss
> +  line-height: 24px;
А тут точно только line-height меняется, без font-size? Обычно эти правила идут в паре

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/header.scss
> +.sale-nav__item:not(:last-of-type) {
Оч сложно, давай лучше использовать класс)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/modal.scss
> +.form-choice-size__title {
Нужно вынести в отдельный файл

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/page-footer.scss
>  .footer-container {
Нужно вынести в отдельный файл

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/page-footer.scss
> +.social-list__item:not(:last-of-type) {
Оч сложно) давай заменим на класс?)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/page-footer.scss
> +  svg {
По БЭМ нельзя стилизовать теги, а только классы)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/product-week.scss
> +.product-week-container {
Нужно вынести в отдельный файл)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/product-week.scss
> +    z-index: 5;
А тут зачем z-index? Не вижу правил, меняющих позиционирование селектора)

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/product-week.scss
>  .product-week__text {
Непонятное имя элемента — что за «текст»?

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/promo-block.scss
> +    &::before {
Нужно изменить вложенность — вложить медиа-выражения внутрь псевдоэлемента

2021-04-18 18:11 UTC, undgrnd commented on source/sass/blocks/promo-block.scss
> +  &:nth-of-type(1) {
Давай заменим на классы)

2021-04-18 18:24 UTC, stanislauhvozdz commented on source/index.html
>        <nav class="sale-nav">
Тогда есть мини вопрос, т.к все списки в хэдаре однотипные +-, нельзя ли сделать их одним блоком, а уже менять их от модификатора? 
пример: header-list(для всех списков) header-list--main, header-list--user, header-list--sale ?

2021-04-19 18:15 UTC, stanislauhvozdz commented on source/sass/fonts.scss
> +  src: url("../fonts/opensans.woff2"), url("../fonts/opensans.woff");
Формат шрифтов должен быть woff2 и woff.
из критериев

2021-04-19 18:20 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +$font-family-primary: "Open Sans", "Arial", sans-serif;
Но это же переменная? с помощью её я прописываю стили в css, а в файле fonts.scss я же подключаю только (1-2-3 шрифта), мне кажется это чуть-чуть разное, не так ли? Или я ошибаюсь

2021-04-19 18:22 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +$mobile: 320px;
аналогично со шрифтами, по мне это переменная. Или я не прав? 
По факту мы создадим еще один файл с  переменными только название будет другое breadpoints.scss

2021-04-19 18:23 UTC, stanislauhvozdz commented on source/sass/variables.scss
> +// colors
Изложил своё позицию чуть выше))

2021-04-19 18:29 UTC, stanislauhvozdz commented on source/sass/common.scss
> +.visually-hidden {
Хорошо)) но это же не блок по факту)
Это общие настройки как по мне, может я конечно ошибаюсь)

2021-04-19 18:31 UTC, stanislauhvozdz commented on source/sass/common.scss
> +  box-sizing: inherit;
на page повесил класс box-sizing: border-box, а это чтоб наследовало по всему дереву

2021-04-19 18:34 UTC, stanislauhvozdz commented on source/sass/common.scss
> +  min-width: $mobile;
чтобы смотрелось однотипно? ) вроде оно особо роли не играет )

2021-04-19 18:39 UTC, stanislauhvozdz commented on source/sass/common.scss
> +    max-width: $desktop;
ну да + если учесть на мобильной) выглядит глуповато)

2021-04-19 18:41 UTC, stanislauhvozdz commented on source/sass/common.scss
> +  min-width: $mobile;
поставил просто width, чет сломало)) вернул назад)

2021-04-19 18:42 UTC, stanislauhvozdz commented on source/sass/common.scss
> +    padding: 0 50px;
убрал до того как дошел до этого комента) но замечание справедливое )

2021-04-19 18:47 UTC, stanislauhvozdz commented on source/sass/blocks/promo-block.scss
> +  margin-top: -35px;
Сделал его элементом)) с элементом думаю можно оставить все те стили что есть сейчас))

2021-04-19 18:49 UTC, stanislauhvozdz commented on source/sass/blocks/promo-block.scss
> +    .br {
имеется ввиду тэг БР ?

2021-04-19 18:54 UTC, stanislauhvozdz commented on source/sass/blocks/promo-block.scss
> +  position: absolute;
я придумал только такое решение, а как лучше поступить в таком случаи?) исправлю)

2021-04-19 19:00 UTC, stanislauhvozdz commented on source/sass/blocks/promo-block.scss
> +.promo-block-container {
Удалил его из-за ненадобности, нашел другой способ, добавил в ХТМЛ container--no-padding

2021-04-19 19:03 UTC, stanislauhvozdz commented on source/sass/blocks/product-week.scss
> +.product-week-container {
Сделал его эл-том блока product-week

2021-04-19 19:24 UTC, stanislauhvozdz commented on source/sass/blocks/page-footer.scss
> +.social-list {
Сделал элементом)

2021-04-19 19:26 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +.delivery-slogan {
Уже эл-т))

2021-04-19 19:28 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  display: none;
уже он стал элементом, добавил модификатор

2021-04-19 19:39 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +.sale-nav {
вынес в отдельный блок, добавил модификатор для скрытия

2021-04-19 19:39 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  display: none;
добавил модификатор для скрытия

2021-04-19 19:43 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +    display: inline-block;
заменил на просто блок

2021-04-19 19:44 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  margin-left: 76px;
чтобы выравнять сокласно пиксель-перфект

2021-04-19 19:46 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  &--active {
он служит для того, когда мы в мобильной версии и нажмем на бургер, он появился , изанчально он скрыт

2021-04-19 19:47 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  box-shadow: 0 1px 0 #ececec, inset 0 1px 0 #ececec;
упустил) сорян, стараюсь это контрольровать)

2021-04-19 19:51 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  &--active {
он служит для того, когда мы в мобильной версии и нажмем на бургер, он появился , изанчально он скрыт, заменил на HIdden

2021-04-19 19:54 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +    display: inline-block;
заменил на block

2021-04-19 19:55 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +    position: absolute;
не нашел способа чтобы по другому решить это, если не сложно подскажи еще вариант, исправлю

2021-04-19 20:06 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +    right: calc(100% / 2 - 525px);
ввел, но она ломает calc ((

2021-04-19 20:09 UTC, stanislauhvozdz commented on source/js/navigation-toggle.js
> +const mainNavigation = document.querySelector('.main-nav');
Получается, будет user-navigation.js и main-navigation.js ?

2021-04-19 20:14 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +    right: calc(100% / 2 - 525px);
Оставил пока цифру 525px

2021-04-19 20:25 UTC, stanislauhvozdz commented on source/index.html
>        <nav class="sale-nav">
Отвязал от названия, minor-navigation получилось)

2021-04-19 20:26 UTC, stanislauhvozdz commented on source/index.html
> +        <picture>
Добавлен

2021-04-19 20:31 UTC, stanislauhvozdz commented on source/index.html
>          <h1 class="promo-block__title">Милые штуки <br class="br"> ручной <br class="br"> работы для дома</h1>
&nbsp;
избалвился

2021-04-19 20:32 UTC, stanislauhvozdz commented on source/index.html
>          <h1 class="promo-block__title">Милые штуки <br class="br"> ручной <br class="br"> работы для дома</h1>
Добавил неразрывных пробелов "&nbs p;"

2021-04-19 20:33 UTC, stanislauhvozdz commented on source/sass/blocks/product-week.scss
> +.product-week-container {
унесен в элемент блока) файл не нужен)

2021-04-19 20:35 UTC, stanislauhvozdz commented on source/sass/blocks/product-week.scss
> +    z-index: 5;
если не указать з-индекс, то текст залазит под "соседнню грид-ячейку" (картинку) , ставлю чтоб текст поднялся над картинкой

2021-04-19 20:37 UTC, stanislauhvozdz commented on source/sass/blocks/product-week.scss
>  .product-week__text {
исправлен) уже будет __description

2021-04-19 20:47 UTC, stanislauhvozdz commented on source/sass/blocks/promo-block.scss
> +  &:nth-of-type(1) {
Изменено на классы

2021-04-21 15:10 UTC, stanislauhvozdz commented on source/index.html
> +            <a class="promo-block__link" href="#">Предметы <br> интерьера</a>
Избавился от БР , добавил ширину и инлайн-блок

2021-04-21 15:16 UTC, stanislauhvozdz commented on source/index.html
> +        <h2 class="product-week__title">ТОВАР НЕДЕЛИ</h2>
Исправил с помощью "ордер"

2021-04-21 15:17 UTC, stanislauhvozdz commented on source/index.html
> +        <h2 class="product-week__title">ТОВАР НЕДЕЛИ</h2>
Исправил, добавил text-uppercase

2021-04-21 15:22 UTC, stanislauhvozdz commented on source/index.html
> +          <li class="about-us__item">Экологически <br> чистые материалы</li>
если избавимся , то будет не получается сделать в соответсвии с макетом. Играя шириной каждого пункта меню, мы не получим такие же переносы

2021-04-21 15:24 UTC, stanislauhvozdz commented on source/index.html
> +    <section class="contacts contacts-container">
Согласен, я его даже не где не использую

2021-04-21 15:24 UTC, stanislauhvozdz commented on source/index.html
> +        <picture>
Добаавил

2021-04-21 15:28 UTC, stanislauhvozdz commented on source/index.html
> +        <svg class="footer__logo-svg" width="86" height="35">
переименовал

2021-04-21 15:31 UTC, stanislauhvozdz commented on source/sass/blocks/about-us.scss
> +    margin-bottom: 82px;
перенес все внешние правила в отдельный класс

2021-04-21 15:31 UTC, stanislauhvozdz commented on source/sass/blocks/about-us.scss
> +    margin-bottom: 85px;
перенес все внешние правила в отдельный класс

2021-04-21 15:34 UTC, stanislauhvozdz commented on source/sass/blocks/about-us.scss
> +    margin-left: calc(((100% - 768px) / 2.183) + 50px);
в принцыпе его можно совсем удалить)) он влият только на плавное увелчние маржина от планшетной версии к версии для пк, просто с этим "страшилой" все плавно двигатеся, без скачков )

2021-04-21 15:41 UTC, stanislauhvozdz commented on source/sass/blocks/about-us.scss
> +  &:nth-child(1)::before {
заменил на класс+модификатор

2021-04-21 15:43 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +    margin-top: 163px;
перенес все внешние правила в отдельный класс

2021-04-21 15:49 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +  margin-bottom: 28px;
Может не стоит? мне форма записи margin: 12px 9px 23px 11px; не сильно нравится, она плохо читаема, надо подсчить какое по порядку значение, представить за какую сторону оно отвчает, друго дело margin-right, сразу понятно )

2021-04-21 15:52 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
>  .contacts-list {
Сделан эл-том

2021-04-21 15:53 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +  margin-bottom: 62px;
сделан эл-том

2021-04-21 15:53 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +    margin-bottom: 48px;
сделан эл-том

2021-04-21 15:59 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +  &:not(:last-of-type) {
Мне кажется не стоит) потому что если доавим случайно еще ддин пункт списка, надо будет опят класс добавлять, а так сколько не добавляй пунктоу в последнего будет нужные нам свойства

2021-04-21 16:00 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +  img {
исправил, перенес в класс

2021-04-21 16:02 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
>  .contacts-map {
перенес в отдельный файл)

2021-04-21 16:03 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +  @media (min-width: $tablet) {
исправил

2021-04-21 16:12 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
> +    margin-bottom: 115px;
Вынес в отдельный класс)

2021-04-21 16:13 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
>  .customer-feedback-container {
Исправил) сделал эл-т)

2021-04-21 16:13 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
> +  @media (min-width: $tablet) {
исправлено

2021-04-21 16:15 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
> +    padding-left: calc(((100% - 768px) / 2.183) + 50px);
в принцыпе его можно совсем удалить)) он влият только на плавное увелчние маржина от планшетной версии к версии для пк, просто с этим "страшилой" все плавно двигатеся, без скачков )

2021-04-21 16:17 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
>  .blockquote__author {
Согласеен)) вынес

2021-04-21 16:18 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
> +    margin-top: calc((((100% - 768px) * 0.0419) * -1) + 60px);
в принцыпе его можно совсем удалить)) просто с этим "страшилой" все плавно двигатеся, без скачков )

2021-04-21 16:19 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
>  .slider-control__prev,
вынес

2021-04-21 16:20 UTC, stanislauhvozdz commented on source/sass/blocks/customer-feedback.scss
>  .slider-control__prev,
готово

2021-04-21 16:21 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
>  .page-header-container {
уже стал эл-том)

2021-04-21 16:21 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
>  .page-header-container {
переименовал

2021-04-21 16:22 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +.page-header {
переименовал

2021-04-21 16:36 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +      span {
заменил на классы

2021-04-21 16:36 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  span {
заменил на классы

2021-04-21 16:41 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +  line-height: 24px;
Исправил

2021-04-21 16:42 UTC, stanislauhvozdz commented on source/sass/blocks/header.scss
> +.sale-nav__item:not(:last-of-type) {
Мне кажется не стоит) потому что если доавим случайно еще ддин пункт списка, надо будет опят класс добавлять, а так сколько не добавляй пунктоу в последнего будет нужные нам свойства

2021-04-21 16:43 UTC, stanislauhvozdz commented on source/sass/blocks/modal.scss
> +.form-choice-size__title {
вынес

2021-04-21 16:44 UTC, stanislauhvozdz commented on source/sass/blocks/page-footer.scss
>  .footer-container {
сделал

2021-04-21 16:44 UTC, stanislauhvozdz commented on source/sass/blocks/page-footer.scss
> +.social-list__item:not(:last-of-type) {
Мне кажется не стоит) потому что если доавим случайно еще ддин пункт списка, надо будет опят класс добавлять, а так сколько не добавляй пунктоу в последнего будет нужные нам свойства

2021-04-21 16:46 UTC, stanislauhvozdz commented on source/sass/blocks/page-footer.scss
> +  svg {
сделал изменение по класу

2021-04-21 18:40 UTC, stanislauhvozdz commented on source/sass/blocks/contacts.scss
> +    left: 290px;
Сделал на гридах)

2021-04-22 11:54 UTC, merged